/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                "tertiary-fixed-dim": "#ffb786",
                "background": "#f8f9fa",
                "on-secondary-fixed-variant": "#474746",
                "on-secondary-fixed": "#1c1b1b",
                "inverse-on-surface": "#f0f1f2",
                "surface-dim": "#d9dadb",
                "on-secondary-container": "#636262",
                "outline-variant": "#c2c6d6",
                "on-tertiary-fixed-variant": "#723600",
                "surface-container-high": "#e7e8e9",
                "on-tertiary": "#ffffff",
                "surface-bright": "#f8f9fa",
                "secondary-container": "#e2dfde",
                "surface-container-low": "#f3f4f5",
                "on-secondary": "#ffffff",
                "on-primary-container": "#fefcff",
                "on-surface": "#191c1d",
                "on-error": "#ffffff",
                "error": "#ba1a1a",
                "outline": "#727785",
                "on-primary-fixed-variant": "#004395",
                "secondary-fixed": "#e5e2e1",
                "secondary": "#5f5e5e",
                "primary-fixed": "#d8e2ff",
                "on-primary": "#ffffff",
                "surface": "#f8f9fa",
                "surface-container": "#edeeef",
                "on-tertiary-fixed": "#311400",
                "on-tertiary-container": "#fffbff",
                "on-background": "#191c1d",
                "surface-container-highest": "#e1e3e4",
                "tertiary-container": "#b75b00",
                "tertiary": "#924700",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#001a42",
                "surface-tint": "#005ac2",
                "secondary-fixed-dim": "#c8c6c5",
                "surface-variant": "#e1e3e4",
                "error-container": "#ffdad6",
                "primary-fixed-dim": "#adc6ff",
                "on-surface-variant": "#424754",
                "on-error-container": "#93000a",
                "inverse-primary": "#adc6ff",
                "tertiary-fixed": "#ffdcc6",
                "inverse-surface": "#2e3132",
                "primary-container": "#2170e4",
                "primary": "#0058be"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            spacing: {
                "margin-mobile": "16px",
                "floating-gap": "20px",
                "unit": "4px",
                "margin-desktop": "40px",
                "container-max": "1280px",
                "gutter": "24px"
            },
            fontFamily: {
                "display-lg-mobile": ["Inter"],
                "code": ["Inter"],
                "body-lg": ["Inter"],
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
                "display-lg": ["Inter"],
                "headline-md": ["Inter"]
            },
            fontSize: {
                "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                "code": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
                "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
                "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
                "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }]
            }
        },
    },
};
